swagger: "2.0"

info:
  title: testing
  version: "1.0"

consumes:
  - application/json
produces:
  - application/json

paths:

  /arraytest:
    get:
      operationId: app.arraytest
      responses:
        200:
          description: send back input
      parameters:
        - name: names
          in: query
          required: true
          type: array
          items:
            type: string
          collectionFormat: csv
#          collectionFormat: multipaths:

  /booltest:
    get:
      operationId: app.booltest
      responses:
        200:
          description: send back input
      parameters:
        - name: mybool
          in: query
          required: true
          type: boolean

  /bodytest:
    post:
      operationId: app.bodytest
      responses:
        200:
          description: send back input
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TestObj'

definitions:
  TestObj:
    type: object
    required:
      - names
      - mybool
    properties:
      names:
        type: array
        items:
          type: string
      mybool:
        type: boolean
